# Generated by Django 5.2.4 on 2025-07-10 09:39

from django.db import migrations

import phonenumbers


def fill_owners_pure_phone_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats_to_update = []

    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                phone_number = phonenumbers.parse(flat.owners_phonenumber, region='RU')
            except phonenumbers.NumberParseException:
                continue

            if phonenumbers.is_valid_number(phone_number):
                flat.owners_pure_phone = (
                    phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
                )
                flats_to_update.append(flat)

    if flats_to_update:
        Flat.objects.bulk_update(flats_to_update, ['owners_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(fill_owners_pure_phone_fields)
    ]
