# Generated by Django 5.2.4 on 2025-07-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
