# Generated by Django 5.2.4 on 2025-07-10 11:55

from django.db import migrations


def fill_owners_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber,
            pure_phone_number=flat.owners_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_owner_flats'),
    ]

    operations = [
        migrations.RunPython(fill_owners_fields)
    ]
