# Generated by Django 5.2.4 on 2025-07-12 06:23

from django.db import migrations


def fill_owners_flats_fields(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber,
            pure_phone_number=flat.owners_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_owner_name_alter_owner_phone_number_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats_fields)
    ]
