# Generated by Django 5.2.4 on 2025-07-14 10:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_remove_flat_owner_remove_flat_owners_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='RU', verbose_name='Номер владельца'),
        ),
    ]
