# Generated by Django 5.2.4 on 2025-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_remove_owner_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
